name: urban_match
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_native_splash: ^2.3.13
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.0
  pretty_dio_logger: ^1.3.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/github.png
  android: true
  ios: true
  android_12:
    color: "#FFFFFF"
    icon_background_color: "#FFFFFF"
    image: assets/images/github.png

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/icons/
    - assets/images/
